## Exercise_1 . Create an  3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.



In [2]:
import numpy as np

arr = np.random.randint(0, 10, size=(4, 5, 3))

print("3D Array:\n", arr)

print("Shape of array:", arr.shape)
print("dimention of array:", arr.ndim)

3D Array:
 [[[8 9 6]
  [5 9 4]
  [4 4 5]
  [0 2 7]
  [5 2 6]]

 [[0 2 9]
  [9 3 5]
  [8 1 2]
  [2 7 1]
  [5 8 5]]

 [[8 9 4]
  [8 0 9]
  [1 5 2]
  [8 3 0]
  [9 5 7]]

 [[6 1 2]
  [1 4 7]
  [4 6 3]
  [3 6 5]
  [1 1 5]]]
Shape of array: (4, 5, 3)
dimention of array: 3


## Exercise_2 . change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions!


In [13]:
import numpy as np

arr = np.random.randint(0, 10, size=(4, 5, 3))
print("Original shape:", arr.shape)

reshaped_arr = arr.reshape(20, 3)
print("Reshaped array:\n", reshaped_arr)

print("New shape:", reshaped_arr.shape)
print("dimention of array:",reshaped_arr.ndim )

Original shape: (4, 5, 3)
Reshaped array:
 [[9 0 6]
 [3 4 7]
 [3 3 3]
 [1 2 8]
 [8 5 4]
 [5 5 4]
 [3 1 9]
 [1 6 5]
 [8 5 5]
 [3 4 9]
 [8 1 5]
 [1 8 3]
 [3 9 9]
 [7 1 2]
 [1 1 5]
 [7 5 2]
 [3 5 7]
 [0 1 9]
 [7 7 5]
 [4 9 9]]
New shape: (20, 3)
dimention of array: 2


## Exercise_3 .  index and print the number 50 from the arr.
## arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])


In [5]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(arr[1,0])

50


##  Exercise_4 . Change the element datatype  of the arr to float!
## arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])


In [8]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print('datatype is : ' ,arr.dtype)
arr = arr.astype(float)
print('new datatype is : ' , arr.dtype)

datatype is :  int64
new datatype is :  float64


## Exercise_5 .  join arr1 and arr2 into a single array!
 ## arr1 = np.array([1, 2, 3])
 ## arr2 = np.array([4, 5, 6])

In [11]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print('join arr1 and arr2 into a single array :',arr)

join arr1 and arr2 into a single array : [1 2 3 4 5 6]
